### PR TITLE
Updated Skeleton App to ZF defaults and added missing package to config file

### PR DESCRIPTION
**Pull request by wshafer**

### CODE REVIEW

**Comment by jerv13** [comment]
I think the "data" folder should be in .gitignore

**Comment by rodmcnew** [comment]
I am thinking the public folder of the skel app should only contain two files:
index.php
.htaccess

Shouldn't all other filed be in the default theme's public folder? What do you think Westin?

**Comment by wshafer** [comment]
@jerv13 - lol.  I had the data folder in the .gitignore.  You removed it yesterday.  lol

@rodmcnew - That how it was originally.  The problem was I had no idea if the create-project worked at all or not.  This will be fine either way once we have the installer package.

With that said, it's hard to work on the app right now with nothing in public.   I spent 2 hours wasting time trying to figure out if the app was installed and server ok.  For that reason I restored the original ZF skeleton so we had something to test.

After having to deal with this, I say we keep this Skeleton as close to the original as we can.  While it won't make any difference to the end users, it makes a huge difference for anyone trying to work on the installer.

In addition, having a working Skeleton app, with a working ZF2 module has really helped me to identify issues in core, where core is breaking existing ZF2 apps when it should stay out of the way until you need it and have it configured.

**Comment by rodmcnew** [comment]
I thought I saw Westin delete the data folder from .gitignore yesterday but we pulled it anyways.

Whatever happened I created https://github.com/reliv/rwriter/pull/5 to re-add it to git ignore

**Comment by rodmcnew** [comment]
@jerv13 James what do you think about leaving the zend skel apps assets in the rwriter skel apps public folders?

**Comment by jerv13** [comment]
Our skeleton app will not be exactly like a ZF2 app.  We are using Bower, composer and asset manager to create these client dependencies.

**Comment by rodmcnew** [comment]
@wshafer In light of @jerv13's  comment. Would just added the default theme as a dependency of this module solve your issues?

**Comment by jerv13** [comment]
I think so

**Comment by wshafer** [comment]
No.  The default theme has no actual controller, layout, or design.  That is RCM specific and can not work with out the full CMS.  That means there's no fallback 404 and error page.  If the install script is broken for some reason, what is the end user going to see?

I think we need something here.  Perhaps it's an RCM specific theme down the road, but I doubt any of us have time to do that atm.  For the time being I suggest that we use the default ZF2 application module to fill in this hole until we have time to make this more RCM like.

**Comment by wshafer** [comment]
@rodmcnew - I reread your original comment and I understand what you're asking here.  The question, should it be in the default theme package?   Maybe.  I'll move these files out to the default theme package and we'll see how that looks.

**Pull request closed without merging**
